#!/bin/bash

TOKEN="XXXXXXXX"
YOUR_ID="YYYYYYYY"

if [ "$1" != "" ]; then
	MESSAGE=$1
else
	MESSAGE="Test"
fi

curl -s --data "chat_id=$YOUR_ID&text=$MESSAGE" https://api.telegram.org/bot$TOKEN/sendMessage > /dev/null

